import {z} from 'zod';

export const UserSchema = z.object({
  id: z.number().optional(), // ID is generated by the backend, optional for POST
  firstName: z.string().nonempty('First Name is required.'),
  lastName: z.string().nonempty('First Name is required.'),
  email: z.string().email('Invalid email address format.').optional(),
  phoneNumber: z.string().optional(),
  birthDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Date must be in YYYY-MM-DD format.'),
  role: z.enum(['admin', 'editor', 'viewer']),
  //TODO: Mandatory Complexity: Conditional Validation Based on Role
});
/**
 * Type for a complete User object (used for GET responses).
 */
export type User = z.infer<typeof UserSchema>;

/**
 * Type for the data transfer object (DTO) used for creation/updates (used for POST body).
 * We make 'id' required for type consistency in the app, but optional in the schema for validation.
 */
export type UserDto = Omit<User, 'id'> & { id?: string };
