import { z } from 'zod';

export const UserValidRoles = ['admin', 'editor', 'viewer'] as const;

// Base schema for a user
const BaseUserSchema = z.object({
  id: z.number().optional(), // ID is generated by the backend, optional for POST
  firstName: z.string().nonempty('First Name is required.'),
  lastName: z.string().nonempty('Last Name is required.'),
  email: z.string().email('Invalid email address format.').optional(),
  phoneNumber: z.string().optional(),
  birthDate: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, 'Date must be in YYYY-MM-DD format.') // ISO date-only format
    .optional(),
  role: z.enum(UserValidRoles),
});

// Shared refinement logic applied to both full and create schemas
const roleBasedRefinement = (
  data: z.infer<typeof BaseUserSchema>,
  ctx: z.RefinementCtx
) => {
  const role = data.role;
  const hasPhone = !!data.phoneNumber && data.phoneNumber.trim().length > 0;
  const hasBirth = !!data.birthDate && data.birthDate.trim().length > 0;

  if (role === 'admin') {
    if (!hasPhone) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'Phone number is required for admin.',
        path: ['phoneNumber'],
      });
    }
    if (!hasBirth) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'Birth date is required for admin.',
        path: ['birthDate'],
      });
    }
  } else if (role === 'editor') {
    if (!hasPhone) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: 'Phone number is required for editor.',
        path: ['phoneNumber'],
      });
    }
  }
};

// Role-dependent validation using superRefine so it works identically in frontend and backend
export const UserSchema = BaseUserSchema.superRefine(roleBasedRefinement);

/**
 * Type for a complete User object (used for GET responses).
 */
export type User = z.infer<typeof UserSchema>;

/**
 * Schema used for creating/updating users from clients (no id provided in the POST body).
 * Keeps the same conditional validation rules as UserSchema.
 */
export const CreateUserSchema = BaseUserSchema.omit({ id: true }).superRefine(
  roleBasedRefinement
);

/**
 * Type for the data transfer object (DTO) used for creation/updates (used for POST body).
 * We make 'id' required for type consistency in the app, but optional in the schema for validation.
 */
export type UserDto = Omit<User, 'id'> & { id?: number };
